server:
  port: 10001

spring:
  application:
    name: service-tracking
    #服务应用名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  httpclient:
    connection-timeout: 3000
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true